version: 1.0.{build}

configuration:
 - Release

clone_folder: c:\AliveHookManager

build_script:
 - cd c:\AliveHookManager\AliveHookManager
 - msbuild AliveHookManager.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m

artifacts:
 - path: '**\*.exe'
   name: AliveHookManager-$(configuration)-$(APPVEYOR_REPO_COMMIT)

test: off
